'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, supabasePublic } from '../../../lib/supabase';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ChevronRight, IndianRupee, Users, CalendarDays, Clock3, Target, UserRound, TrendingUp } from 'lucide-react';

type Tx = { id:string; customer_id:string; customer_name:string|null; amount_paid:number; payment_mode:string; served_at:string; staff_id:string; service_id:string; customers:{name:string}|null; profiles:{name:string}|null; services:{name:string}|null };
type Outlet = {id:string;name:string;city:string};

export default function Insights(){
 const router=useRouter(); const [tx,setTx]=useState<Tx[]>([]); const [outlets,setOutlets]=useState<Outlet[]>([]); const [outletId,setOutletId]=useState(''); const [selectedCustomer,setSelectedCustomer]=useState<string|null>(null); const [selectedService,setSelectedService]=useState<string|null>(null); const [selectedStaff,setSelectedStaff]=useState<string|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/signin');return;} const {data:p}=await supabasePublic.rpc('get_my_profile'); const profile=Array.isArray(p)?p[0]:p; const {data:o}=await supabase.rpc('owner_list_outlets'); const os=(o||[]).filter((x:any)=>x.active); setOutlets(os); const chosen=profile?.outlet_id||os[0]?.id; setOutletId(chosen||''); if(chosen){const {data}=await supabase.from('transactions').select('id,customer_id,customer_name,amount_paid,payment_mode,served_at,staff_id,service_id,customers(name),profiles(name),services(name)').eq('outlet_id',chosen).order('served_at',{ascending:false}).limit(5000);setTx((data||[]) as any);} setLoading(false)})()},[router]);
 const money=(n:number)=>'₹'+Math.round(n||0).toLocaleString('en-IN');
 const customerMap=useMemo(()=>{const m:Record<string,{id:string,name:string,spend:number,visits:number,dates:number[]}>={}; tx.forEach(t=>{const id=t.customer_id; if(!id)return; m[id]??={id,name:t.customer_name||t.customers?.name||'Unknown',spend:0,visits:0,dates:[]};m[id].spend+=Number(t.amount_paid);m[id].visits++;m[id].dates.push(new Date(t.served_at).getTime())});return Object.values(m).map(c=>{c.dates.sort((a,b)=>b-a);const gaps:number[]=[];for(let i=1;i<c.dates.length;i++)gaps.push((c.dates[i-1]-c.dates[i])/86400000);const avgGap=gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:null;const days=Math.floor((Date.now()-c.dates[0])/86400000);return {...c,avgBill:c.spend/c.visits,avgGap,days}}).sort((a,b)=>b.spend-a.spend)},[tx]);
 const selected=customerMap.find(c=>c.id===selectedCustomer); const customerTx=selected?tx.filter(t=>t.customer_id===selected.id):[];
 const serviceMap=useMemo(()=>group(tx,t=>t.services?.name||'Unknown service'),[tx]); const staffMap=useMemo(()=>group(tx,t=>t.profiles?.name||'Unknown staff'),[tx]);
 const drillTx=selectedService?tx.filter(t=>(t.services?.name||'Unknown service')===selectedService):selectedStaff?tx.filter(t=>(t.profiles?.name||'Unknown staff')===selectedStaff):tx;
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#F7F4EF]">Loading intelligence…</div>;
 return <main className="min-h-screen bg-[#F7F4EF] p-5 text-[#17130F] md:p-8"><div className="mx-auto max-w-[1500px]">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><button onClick={()=>router.push('/dashboard')} className="mb-4 flex items-center gap-2 text-sm text-[#756B62]"><ArrowLeft size={16}/> Back to dashboard</button><p className="text-xs font-bold uppercase tracking-[.25em] text-[#8B6B4A]">Business intelligence</p><h1 className="mt-2 text-4xl font-bold">Drill-down analytics</h1><p className="mt-2 text-sm text-[#756B62]">Every number can be traced back to staff, service and customer activity.</p></div><select value={outletId} onChange={async e=>{setOutletId(e.target.value);const {data}=await supabase.from('transactions').select('id,customer_id,customer_name,amount_paid,payment_mode,served_at,staff_id,service_id,customers(name),profiles(name),services(name)').eq('outlet_id',e.target.value).order('served_at',{ascending:false}).limit(5000);setTx((data||[]) as any)}} className="rounded-md border border-[#dfd3c5] bg-white px-4 py-3 text-sm">{outlets.map(o=><option key={o.id} value={o.id}>{o.name} — {o.city}</option>)}</select></div>
  <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Revenue" value={money(tx.reduce((a,t)=>a+Number(t.amount_paid),0))} icon={<IndianRupee/>}/><Stat title="Customers" value={customerMap.length.toLocaleString('en-IN')} icon={<Users/>}/><Stat title="Transactions" value={tx.length.toLocaleString('en-IN')} icon={<CalendarDays/>}/><Stat title="Avg bill" value={money(tx.length?tx.reduce((a,t)=>a+Number(t.amount_paid),0)/tx.length:0)} icon={<TrendingUp/>}/></div>
  <section className="mt-6 rounded-md border border-[#DED6CC] bg-white p-6"><h2 className="font-bold">Revenue → service → staff → customer</h2><p className="mt-1 text-xs text-[#756B62]">Select a service or staff member to narrow the transaction table.</p><div className="mt-5 grid gap-6 lg:grid-cols-2"><Drill title="Services" rows={serviceMap} selected={selectedService} onSelect={x=>{setSelectedService(selectedService===x?null:x);setSelectedStaff(null)}} money={money}/><Drill title="Staff" rows={staffMap} selected={selectedStaff} onSelect={x=>{setSelectedStaff(selectedStaff===x?null:x);setSelectedService(null)}} money={money}/></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-[#EDE7DF] text-left text-xs text-[#756B62]"><th className="pb-3">Date</th><th>Customer</th><th>Service</th><th>Staff</th><th>Payment</th><th className="text-right">Amount</th></tr></thead><tbody>{drillTx.slice(0,50).map(t=><tr key={t.id} className="border-b border-[#f0ebe5]"><td className="py-3">{new Date(t.served_at).toLocaleDateString('en-IN')}</td><td className="font-semibold">{t.customer_name||t.customers?.name||'Unknown'}</td><td>{t.services?.name||'Unknown'}</td><td>{t.profiles?.name||'Unknown'}</td><td>{t.payment_mode}</td><td className="text-right font-bold">{money(Number(t.amount_paid))}</td></tr>)}</tbody></table></div></section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-md border border-[#DED6CC] bg-white p-6"><div className="flex items-center gap-2"><UserRound size={18}/><h2 className="font-bold">Customer 360</h2></div><p className="mt-1 text-xs text-[#756B62]">Click a customer to see lifetime behaviour and visit history.</p><div className="mt-5 grid max-h-[520px] grid-cols-1 gap-2 overflow-auto">{customerMap.slice(0,100).map(c=><button key={c.id} onClick={()=>setSelectedCustomer(c.id)} className={`flex items-center justify-between rounded-md border p-4 text-left ${selectedCustomer===c.id?'border-[#8B6B4A] bg-[#f7f0e7]':'border-[#EDE7DF] bg-white'}`}><span><b>{c.name}</b><span className="ml-2 text-xs text-[#756B62]">{c.visits} visits</span></span><span className="flex items-center gap-2 text-sm font-bold">{money(c.spend)}<ChevronRight size={15}/></span></button>)}</div></div><div className="rounded-md bg-[#17130F] p-6 text-white">{selected?<><p className="text-xs uppercase tracking-[.2em] text-white/40">Customer 360</p><h2 className="mt-2 text-3xl font-bold">{selected.name}</h2><div className="mt-6 grid grid-cols-2 gap-3"><DarkStat title="Lifetime spend" value={money(selected.spend)}/><DarkStat title="Visits" value={String(selected.visits)}/><DarkStat title="Avg bill" value={money(selected.avgBill)}/><DarkStat title="Days since visit" value={String(selected.days)}/></div><div className="mt-6"><p className="text-xs text-white/40">Normal visit interval</p><p className="mt-1 text-xl font-bold">{selected.avgGap?`${selected.avgGap.toFixed(0)} days`: 'Building history'}</p></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs uppercase tracking-[.2em] text-white/40">Visit history</p><div className="mt-3 space-y-2">{customerTx.slice(0,10).map(t=><div key={t.id} className="flex justify-between rounded-sm bg-white/5 p-3 text-sm"><span>{new Date(t.served_at).toLocaleDateString('en-IN')} · {t.services?.name||'Service'}</span><b>{money(Number(t.amount_paid))}</b></div>)}</div></div></>:<div className="grid h-full min-h-[350px] place-items-center text-center"><div><UserRound className="mx-auto opacity-40" size={42}/><p className="mt-4 font-semibold">Select a customer</p><p className="mt-1 text-sm text-white/50">Their complete recorded behaviour will appear here.</p></div></div>}</div></section>
  <section className="mt-6 grid gap-6 md:grid-cols-3"><Info title="Forecast" icon={<Target/>} text="The main dashboard already projects month-end revenue from current pace and historical monthly data."/><Info title="Capacity" icon={<Clock3/>} text="Peak-hour intelligence identifies the busiest recorded hours. Appointment capacity becomes more precise after appointment statuses are enabled."/><Info title="Profitability + inventory" icon={<IndianRupee/>} text="The repository now contains a migration for service costs and inventory so future reports can calculate contribution and stock alerts from real data."/></section>
 </div></main>
}
function Stat({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <div className="rounded-md border border-[#DED6CC] bg-white p-5"><div className="flex justify-between text-sm text-[#756B62]">{title}<span>{icon}</span></div><div className="mt-4 text-3xl font-bold">{value}</div></div>}
function DarkStat({title,value}:{title:string;value:string}){return <div className="rounded-md bg-white/10 p-4"><div className="text-xl font-bold">{value}</div><div className="mt-1 text-[10px] text-white/50">{title}</div></div>}
function Drill({title,rows,selected,onSelect,money}:{title:string;rows:{name:string;value:number;count:number}[];selected:string|null;onSelect:(x:string)=>void;money:(x:number)=>string}){return <div><div className="mb-3 flex justify-between text-xs text-[#756B62]"><b>{title}</b><span>Click to drill down</span></div><div className="space-y-3">{rows.slice(0,8).map((r,i)=><button key={r.name} onClick={()=>onSelect(r.name)} className={`w-full rounded-md p-3 text-left ${selected===r.name?'bg-[#E8DDD0]':'bg-[#F1ECE5]'}`}><div className="flex justify-between text-sm"><b>{i+1}. {r.name}</b><b>{money(r.value)}</b></div><div className="mt-2 h-2 rounded-full bg-white"><div className="h-full rounded-full bg-[#17130F]" style={{width:`${Math.max(5,r.value/Math.max(...rows.map(x=>x.value),1)*100)}%`}}/></div><div className="mt-1 text-[10px] text-[#756B62]">{r.count} transactions</div></button>)}</div></div>}
function Info({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <div className="rounded-md border border-[#DED6CC] bg-white p-5"><div className="flex items-center gap-2 font-bold">{icon}{title}</div><p className="mt-3 text-xs leading-5 text-[#756B62]">{text}</p></div>}
function group(items:Tx[],key:(t:Tx)=>string){const m:Record<string,{name:string;value:number;count:number}>={};items.forEach(t=>{const name=key(t);m[name]??={name,value:0,count:0};m[name].value+=Number(t.amount_paid);m[name].count++});return Object.values(m).sort((a,b)=>b.value-a.value)}
